### DISCUSSION TITLE
[03.12.2024] Blog 8 - Einrichtung einer CI/CD-Pipeline mit GitHub Actions

### DISCUSSION THREAD

**Discussion by bunki1224** [bunki1224/Softwareengineering-Projekt#51] [Show and tell]
In der vergangenen Woche haben wir erfolgreich eine CI/CD-Pipeline für unsere React-App TripAhead mit GitHub Actions implementiert. Dieser Prozess umfasste die Einrichtung eines selbst gehosteten Runners, das Schreiben eines Deployment-Skripts und die Automatisierung von Builds und Tests. Hier sind die Details unserer Arbeit und die aktuellen Herausforderungen.
## Zielsetzung
Das Ziel war es, eine zuverlässige und automatisierte Lösung zu schaffen, die bei jedem Commit auf den main-Branch oder bei einem Pull Request automatisch die Anwendung baut und testet. Dabei verwenden wir einen selbst gehosteten Runner, um Builds direkt in unserer Infrastruktur auszuführen.

## Setup der Pipeline
Die Pipeline wurde mit dem folgenden GitHub Actions-Skript konfiguriert:
``` yaml
name: Build React App in Tripahead Folder

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checkout des Codes
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Node.js installieren
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # In den Tripahead-Ordner wechseln
      - name: Change directory to TripAhead
        working-directory: TripAhead
        run: echo "Working in TripAhead folder"

      # Abhängigkeiten installieren
      - name: Install dependencies
        working-directory: TripAhead
        run: npm install

      # Build der React-App
      - name: Build React App
        working-directory: TripAhead
        run: npm run build
```
## Schritte der Pipeline

1. Code-Checkout
Mit der Aktion actions/checkout@v3 holen wir den aktuellen Stand des Repositories auf den Runner.

2. Node.js-Setup
Wir verwenden die Aktion actions/setup-node@v3, um Node.js in der Version 20 zu installieren.

3. Verzeichniswechsel
Da sich die React-App im Ordner TripAhead befindet, wechseln wir das Arbeitsverzeichnis.

4. Installation der Abhängigkeiten
Mit npm install stellen wir sicher, dass alle benötigten Pakete für die Anwendung verfügbar sind.

5. Build der App
Zum Abschluss wird die App mit npm run build gebaut.

## Herausforderungen und nächste Schritte
Die Pipeline funktioniert wie geplant, aber die erstellten Build-Dateien werden derzeit noch nicht vom Webserver bereitgestellt. Das bedeutet, dass die fertige Anwendung nicht automatisch für die Endnutzer verfügbar ist.

Nächste Schritte:
Automatische Bereitstellung einrichten
Wir müssen die gebauten Dateien nach dem Build in den Webserver-Verzeichnissen bereitstellen, z. B. durch:

Ein Kopierskript, das die Dateien nach /var/www/html oder ein ähnliches Verzeichnis verschiebt.
Automatische Neustartmechanismen für den Webserver (z. B. Apache, Nginx).
